test: add plain text job_bundle_output_tests
aws-deadline/deadline-cloud-for-cinema-4d pull request #77
Opened 2024-10-25 16:37 UTC by gp-dan

5 test scenes implemented as python scripts and respective job bundles:
- simple physical render
- simple redshift render
- redshift with multipass render
- redhsift with takes
- redshift with texture asset, bmp file generated by python script

### What was the problem/requirement? (What/Why)

Example scenes and respective expected job bundle outputs

### What was the solution? (How)

Plain text py files to generate scenes and their respective job bundle outputs with normalized paths

### What is the impact of this change?

Developers have a common set of test scenes

### How was this change tested?

- Launch Cinema 4D
- Extensions > User Scripts > Run Script ...
- Select script file ./job_bundle_output_tests/<test>/scene/cube.py
- The script builds the scene and saves it to ./job_bundle_output_tests/<test>/scene/<test>.c4d
- Extensions > Deadline Cloud Submitter
- Submit or Export Bundle 

### Was this change documented?

No

### Is this a breaking change?

No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-10-25 19:57 UTC, karthikbekalp requested changes
Thanks for your contribution. I've been able to run the scripts and confirm that the renders work. 
Although the SonarCloud tests are failing, this can be fixed with a simple variable name change.

2024-10-25 19:57 UTC, karthikbekalp commented on job_bundle_output_tests/redshift_textured/scene/cube.py
> +    bitmapShader = c4d.BaseShader(c4d.Xbitmap)
Please update this variable name from `bitmapShader` to `bitmap_shader` (and replace all the occurrences) to pass the SonarCloud checks.

2024-10-29 14:25 UTC, karthikbekalp commented on job_bundle_output_tests/redshift_textured/scene/cube.py
> +    bitmapShader = c4d.BaseShader(c4d.Xbitmap)
Thanks for fixing it!

2024-10-29 14:26 UTC, karthikbekalp commented
Hmm, sorry my bad. Looks like the SonarCloud checks still failed because it detected duplicate code amongst all the tests. I'll see if I can somehow override it.

2024-10-29 14:29 UTC, karthikbekalp commented
But the linting has failed so there's a need to reformat the code anyway. https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/actions/runs/11564466263/job/32191091030?pr=77 
Can you please run 

```
# For fixing the formatting
hatch run fmt

# Add the formatted files
git add ...

# Amend your commit
git commit --amend

# Force push the amended commit
git push --force-with-lease <remote_name> gp-dan:job_bundle_output_tests
```

2024-10-29 17:07 UTC, gp-dan commented
Thanks @karthikbekalp I intentionally kept the duplication as I was trying to make a clean plain text equivalent of a static .c4d scene description.  if we factor out the duplicated lines the scripts will no longer be static scene descriptions but programs that require a util library to run. You'll need to add the util library to the environment before running Extensions > User Scripts > Run Script ... The scenes will no longer be strictly reproducible and self contained tests as the scene descriptions now depend on a utility function that may change and affect all scenes and complicate finding regressions. Could we configure the CI to ignore the duplication requirement on job_bundle_output_tests dir to avoid adding the extra complexity? What do you think?

2024-10-29 19:38 UTC, karthikbekalp commented
Thanks for your clarification. It looks like we can override and merge even if the SonarCloud checks failed.

2024-10-29 19:39 UTC, karthikbekalp approved these changes

2024-10-30 15:06 UTC, lucaseck approved these changes

2024-10-30 15:07 UTC, merged